### PR TITLE
Update releaseAsset.js to fix release download display

### PR DESCRIPTION
**Pull request by sjoerddebruin**
- Lowercase the filename in this function to also work in cases where for example Windows is capitalized
- Add new Ubuntu and Debian versions

### CODE REVIEW

**Comment by GingerAdonis** [comment]
Thank you!

**Comment by sjoerddebruin** [comment]
And thank you for fixing my mistake while being low on coffee ☕

**Comment by GingerAdonis** [comment]
I wanted to make sure the change won't cause side-effects as this code is old and buggy.. 😅

**Comment by Gymnasiast** [comment]
Out of interest, when do you expect these changes to be visible on the live site?

**Comment by GingerAdonis** [comment]
> Out of interest, when do you expect these changes to be visible on the live site?

Right now :)

**Pull request merged**
